service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::larsen5b"
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::larsen5b/*"
        - Effect: "Allow"
          Action: "sqs:*"
          Resource:
            - Fn::GetAtt: [SQSQueue, Arn]
        - Effect: "Allow"
          Action: "sns:*"
          Resource:
            Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-task6
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SNSTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: gimmick.mimik@mail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

functions:
  importProductsFile:
    handler: handlers.importProductsFile
    environment:
      S3_BUCKET: larsen5b
    events:
      - http:
          path: import
          method: post
          cors: true

  importFileParser:
    handler: handlers.importFileParser
    environment:
      S3_BUCKET: larsen5b
    events:
      - s3:
          bucket: larsen5b
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

  catalogBatchProcess:
    handler: handlers.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
